USE cape_codd;
SELECT SKU,SKU_Description FROM INVENTORY;
SELECT SKU_Description,SKU FROM INVENTORY;
SELECT WarehouseID FROM WAREHOUSE;
SELECT DISTINCT WarehouseID FROM WAREHOUSE;
SELECT WarehouseID,SKU,SKU_Description,QuantityOnHand FROM INVENTORY;
SELECT * FROM INVENTORY;
SELECT * FROM INVENTORY HAVING QuantityOnHand >0;
SELECT SKU,SKU_Description,QuantityOnHand = 0 FROM INVENTORY;
SELECT SKU,SKU_Description,WarehouseID,QuantityOnHand = 0 FROM INVENTORY ORDER BY WarehouseID ASC;
SELECT SKU,SKU_Description,WarehouseID,QuantityOnHand > 0 FROM INVENTORY ORDER BY WarehouseID ASC ,SKU DESC;
SELECT SKU,SKU_Description,WarehouseID,QuantityOnHand >= 0 FROM INVENTORY ORDER BY WarehouseID ASC, SKU DESC;
SELECT SKU,SKU_Description,WarehouseID,QuantityOnHand > 1 < 10 FROM INVENTORY;
SELECT SKU,SKU_Description,WarehouseID,QuantityOnHand BETWEEN 1 AND 10 > 1 < 10  FROM INVENTORY;
SELECT DISTINCT SKU,SKU_Description FROM INVENTORY WHERE SKU_Description LIKE 'Half-Dome%';
SELECT DISTINCT SKU,SKU_Description  LIKE 'climb%' FROM INVENTORY ;

